name: app_android
description: Foadmap Facile - Application d'aide Ã  la gestion des FODMAPs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  http: ^1.2.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - code-barre.png
    - Foadmap_Logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "Foadmap_Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "Foadmap_Logo.png"
  min_sdk_android: 21
