name: app_android
description: Une application Flutter basique
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  http: ^1.2.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - code-barre.png

